name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Scan for vulnerabilities
        uses: EmbarkStudios/cargo-deny-action@v1.6.1
        with:
          command: check advisories
            
